spring:
  application:
    name: razorpay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER: postgres}
    password: ${DB_PWD:Nithinreddy9491$}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

