spring:
  application:
    name: razorpay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:Nithinreddy9491$}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

master:
  secret-key: m9K3vL7xQ2pN8sR4tY6uA1bC5dE0fG7hJ2kL9nP3qWs=

payment:
  simulator:
    poll-interval-seconds: 5000
    chaos-mode: FAILURE
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 1
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: sdfkjghdskljhbfvkeshfdnzkljgfdskujlzjfdslbkjfes

app:
  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 2
